In [38]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [47]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [50]:
x = A_inverse @ b
x

array([[ 3.15251974e+15],
       [-6.30503948e+15],
       [ 3.15251974e+15]])

In [52]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[-0.69444444],
       [ 0.05555556],
       [ 0.80555556]])

In [53]:
A @ x - b

array([[-0.16666667],
       [ 0.33333333],
       [-0.16666667]])

In [56]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [58]:
A = X[:4, [0, 4, 5, 6]]
b = y[:4]

In [59]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [61]:
b

array([24. , 21.6, 34.7, 33.4])

In [63]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x         # 'CRIM',        'NOX',         'RM',            'AGE'

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

# 연습문제 2.4.6

In [78]:
w, resid, rank, s = np.linalg.lstsq(X, y)

In [82]:
w = str(w)
w # Crim           # Indus            # Nox           # RooM          # LSTAT         # B        # PTRATIO:학생/교사비율    # ZN           # CHAS            # AGE           # RAD        # DIS            # TAX

'[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00\n -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01\n  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02\n -4.16304471e-01]'

In [ ]:
gh