In [3]:
A  = np.array([[1, -2],[2, -3]])

In [6]:
w, v = np.linalg.eig(A)
print(w, v)

[-0.99999998 -1.00000002] [[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [7]:
v2 = ([[1], [1]])
v2

[[1], [1]]

In [11]:
np.linalg.norm(v2)

1.4142135623730951

In [44]:
B = np.array([[2, 3], [2, 1]])

In [46]:
V_inv = np.linalg.inv(V)

In [45]:
w, V = np.linalg.eig(B)

In [34]:
print(v)
print(w)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [36]:
w

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [37]:
print(np.diag(w))

[0.83205029 0.70710678]


In [48]:
print(V@np.diag(w)@ V_inv)

[[2. 3.]
 [2. 1.]]


In [49]:
C = np.array([[1, 1], [0,1]])

In [50]:
w,V = np.linalg.eig(C)

In [51]:
V_inv = np.linalg.inv(V)

In [53]:
V@np.diag(w)@V_inv

array([[1., 0.],
       [0., 1.]])

# 연습문제 3.3.6

In [56]:
A = np.array([[2,3],[2, 1]])

In [57]:
w, V = np.linalg.eig(A)

In [58]:
V_inv = np.linalg.inv(V)

In [63]:
W = np.diag(w)@np.eye(2)

In [64]:
W_inv = np.linalg.inv(W)

In [65]:
A_inv = V@W_inv@V_inv

In [66]:
A_inv

array([[-0.25,  0.75],
       [ 0.5 , -0.5 ]])