# Symmetric matrix

In [32]:
A = np.array([[60, 30, 20], [30, 20, 15], [20, 15, 12]])
A

array([[60, 30, 20],
       [30, 20, 15],
       [20, 15, 12]])

In [33]:
w, V = np.linalg.eig(A)

In [34]:
w1, w2, w3 = w

In [35]:
V

array([[ 0.82704493,  0.54744843,  0.12765933],
       [ 0.4598639 , -0.52829024, -0.71374689],
       [ 0.32329844, -0.64900666,  0.68867153]])

In [44]:
V1 = V[:,:1]
V1

array([[0.82704493],
       [0.4598639 ],
       [0.32329844]])

In [43]:
V2 = V[:, 1:2]
V2

array([[ 0.54744843],
       [-0.52829024],
       [-0.64900666]])

In [42]:
V3 = V[:, 2:3]
V3

array([[ 0.12765933],
       [-0.71374689],
       [ 0.68867153]])

In [45]:
A1 = V1@V1.T
A2 = V2@V2.T
A3 = V3@V3.T

In [46]:
w1*A1 + w2*A2 + w3*A3

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

In [41]:
w1 * A1

array([[84.49913563]])

In [47]:
np.linalg.inv(A)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [51]:
a = 1/w1 * A1

In [52]:
b = 1/w2 * A2

In [53]:
c = 1/w3 * A3

In [54]:
a + b + c

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

# Scatter Matrix

XX.T

행렬 X 가 풀랭크면 XX.T 의 역행렬이 존재한다