In [2]:
import numpy as np

In [3]:
array  = np.array([1,2,3])

In [5]:
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [6]:
array.ndim

1

In [8]:
array2 = np.array([[1, 2, 3], [4,5,6]])

In [10]:
array2.ndim, array2.shape

(2, (2, 3))

In [11]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array3 = np.array([[[1,2,3], [4,5,6]]])

In [15]:
array3, array3.ndim, array.shape

(array([[[1, 2, 3],
         [4, 5, 6]]]),
 3,
 (3,))

In [16]:
# array data type is only same one 

In [24]:
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# offset index : masking

In [26]:
# broadcasting

boolean condition masking

In [39]:
k = array2 >3
k

array([[False, False, False],
       [ True,  True,  True]])

In [40]:
array2[k] = 100

In [41]:
array2

array([[  1,   2,   3],
       [100, 100, 100]])

In [42]:
array.dtype

dtype('int64')

# Correlation Coefficiency