In [79]:
ls = [1, 2, 3, 4, 5]
ls2 = [5, 6, 7]
ls3 = [9, 10, 11, 12, 14]

In [80]:
def map_func(func, *nums):
    return [func(*data) for data in zip(*nums)]

In [81]:
map_func(lambda *nums : sum(nums), ls1, ls2, ls3)

[15, 18, 21]

In [86]:
def filter_func(func, dataset):
    return [data for data in dataset if func(data)]


In [89]:
filter_func(lambda num : num % 2, ls)

[1, 3, 5]

In [91]:
def reduce_func(func, ls):
    pass
# use 'pop'   

In [92]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [97]:
dataset = np.random.randint(100, 130, (8,8))

In [95]:
np.random.randint(1, 100, (5,5))

array([[ 5,  5, 33, 67, 24],
       [97, 73, 31, 77, 26],
       [53, 80, 35, 37, 52],
       [44, 70, 18, 19, 93],
       [62, 38,  5, 12, 83]])

In [96]:
nparray.astype()

NameError: name 'nparray' is not defined

In [104]:
d1 = dataset % 3 == 0 
d2 = dataset % 5 == 0
d3 = dataset % 15 == 0

In [105]:
dataset[d1]

array([108, 120, 120, 108, 105, 102, 102, 126, 105, 105, 120, 114, 114,
       114, 126, 120])

In [106]:
re_str =  dataset.astype('str')

In [108]:
re_str[d1] = 'fiz'

In [109]:
re_str[d2] = 'buzz'

In [110]:
re_str[d3] = 'fizzbuzz'

In [111]:
re_str

array([['113', '101', '128', '107', 'fiz', '112', '124', 'buzz'],
       ['fizzbuzz', '113', 'fizzbuzz', '118', 'fiz', '101', '127',
        'fizzbuzz'],
       ['101', '128', '119', '103', 'buzz', '119', 'fiz', 'buzz'],
       ['fiz', 'fiz', '124', '119', '119', 'fizzbuzz', '118', 'buzz'],
       ['fizzbuzz', '122', '128', 'fizzbuzz', 'buzz', '109', 'buzz',
        '103'],
       ['113', '118', 'fiz', 'fiz', '107', '101', 'buzz', 'buzz'],
       ['buzz', '124', '127', 'fiz', 'buzz', '109', '103', '103'],
       ['104', '101', '112', 'fiz', 'fizzbuzz', '109', '101', '104']],
      dtype='<U21')

In [113]:
dm = np.random.randint(1,20,(5,5))

In [117]:
mask1 = dm == np.min(dm)

In [118]:
mask2 = dm == np.max(dm)

In [119]:
result = dm.astype('str')

In [121]:
result[mask1] = 'Min'

In [122]:
result[mask2] = 'Max'

In [123]:
result

array([['12', '12', '12', '4', 'Min'],
       ['12', '11', '18', '5', '10'],
       ['5', '3', '11', '8', '4'],
       ['Max', 'Min', '13', '5', '14'],
       ['18', '10', '5', '17', '2']], dtype='<U21')

# linspace, logspace

In [126]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [127]:
# logspace
# log10(x1) = 2, log10(x2) = 3, log10(x3) = 4
np.logspace(2, 4, 3)


array([  100.,  1000., 10000.])

In [128]:
# 30세 연봉 100000, 60세 연봉 1000000
# 연봉이 선형증가, 지수증가 두경우에 40세 와 50세 연봉출력


In [129]:
age30 = 100000
age40 = 1000000

In [130]:
np.linespace(age30, age60, 4)

AttributeError: module 'numpy' has no attribute 'linespace'

In [131]:
np.logsapce()

AttributeError: module 'numpy' has no attribute 'logsapce'

# random seed, rand, randn, randint, suffle, choice

In [140]:
np.random.seed(4)
result = np.random.randint(10, 100, 10)
result

array([56, 65, 79, 11, 97, 82, 60, 19, 68, 65])

In [143]:
np.random.rand(10) # 균등분포

array([0.73338017, 0.40844386, 0.52790882, 0.93757158, 0.52169612,
       0.10819338, 0.15822341, 0.54520265, 0.52440408, 0.63761024])

In [145]:
np.random.randn(10) # 정규분포

array([ 1.69235772, -1.11281215,  1.63574754, -1.36096559, -0.65122583,
        0.54245131,  0.04800625, -2.35807363, -1.10558404,  0.83783635])

In [150]:
r = np.random.randint(1, 10, (3, 4))
r

array([[6, 5, 3, 4],
       [5, 8, 7, 7],
       [9, 1, 4, 6]])

In [149]:
np.random.shuffle(r)
r

array([[5, 7, 9, 5],
       [9, 7, 8, 1],
       [5, 4, 9, 6]])

In [154]:
np.random.choice(5, 10, p=[0.1, 0, 0,4, 0,2, 0,3] ) 

ValueError: 'a' and 'p' must have same size

In [155]:
np.unique(r, return_coutns = True)

TypeError: _unique_dispatcher() got an unexpected keyword argument 'return_coutns'

# matrix concat

## concatenate

In [156]:
na1 = np.random.randint(10, (2,3))
na2 = np.random.randint(10, (3,2))
na3 = np.random.randint(10, (3,3))

ValueError: low >= high

In [158]:
np.concatenate((na1, na3), axis = 1)

NameError: name 'na1' is not defined

# c_, r_

In [160]:
np.c_[np.array([1,2,3]), np.array([4,6,7])]

array([[1, 4],
       [2, 6],
       [3, 7]])

# split, var, std, mean...